In [1]:
#1. Purpose and Advantages of NumPy:  
#NumPy is a library for numerical computations in Python, providing support for large multi-dimensional arrays and matrices along with a collection of mathematical functions to operate on them. It enhances Python's capabilities for numerical operations by offering efficient array computations, element-wise operations, broadcasting, and more, which are optimized and implemented in C.

#2. np.mean() vs. np.average():  
#Both np.mean() and np.average() calculate the arithmetic mean of an array. The difference is that np.average() allows for specifying weights to calculate a weighted mean, while np.mean() does not. Use np.average() when you need to compute a weighted mean; otherwise, np.mean() suffices.

#3. Reversing a NumPy Array:  
#For 1D arrays, you can use slicing: array[::-1]. For 2D arrays, you can reverse rows with np.flipud(array) and columns with np.fliplr(array).

#4. Determining Data Types in NumPy:  
#Use array.dtype to find the data type of elements in a NumPy array. The data type is crucial for memory management and performance, as NumPy arrays are stored in contiguous memory and can use optimized operations based on the data type.

#5. ndarrays in NumPy:  
#ndarrays are the core data structure of NumPy, representing n-dimensional arrays. Key features include support for fast mathematical operations, broadcasting, and a variety of methods for manipulation. They differ from Python lists as they provide more efficient storage and faster computation.

#6. Performance Benefits of NumPy Arrays:  
#NumPy arrays are more efficient for large-scale numerical operations because they use contiguous memory and are implemented in C, reducing the overhead of dynamic typing in Python lists.

#7. vstack() vs. hstack():  
#vstack() stacks arrays vertically (row-wise), while hstack() stacks them horizontally (column-wise). Example:  
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstack_result = np.vstack((a, b))
print("Vertical stack:\n", vstack_result)
hstack_result = np.hstack((a, b))
print("Horizontal stack:\n", hstack_result)

   

#8. fliplr() vs. flipud() Methods:  
#fliplr() flips an array horizontally (left to right), and flipud() flips an array vertically (up to down).

#9. array_split() Method:  
#array_split() splits an array into sub-arrays. It can handle uneven splits by distributing the extra elements among the sub-arrays.

#10. Vectorization and Broadcasting in NumPy:  
#Vectorization allows for applying operations to entire arrays without explicit loops, and broadcasting enables operations between arrays of different shapes by "stretching" the smaller array.



Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack:
 [1 2 3 4 5 6]


In [2]:
#1. Create and Transpose a 3x3 Array:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original array:\n", arr)

# Transpose the array
transposed = arr.T
print("Transposed array:\n", transposed)


Original array:
 [[50 17 94]
 [52 55 11]
 [69 56 65]]
Transposed array:
 [[50 52 69]
 [17 55 56]
 [94 11 65]]


In [3]:
#2. Reshape a 1D Array:
import numpy as np

# Create a 1D array with values from 0 to 9
arr = np.arange(10)
print("Original array:\n", arr)

# Reshape the array to shape (2, 5)
reshaped_2_5 = arr.reshape(2, 5)
print("Reshaped to (2, 5):\n", reshaped_2_5)

# Reshape the array to shape (5, 2)
reshaped_5_2 = reshaped_2_5.reshape(5, 2)
print("Reshaped to (5, 2):\n", reshaped_5_2)


Original array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped to (2, 5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped to (5, 2):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
#3. 4x4 Array with Zero Border:
import numpy as np
arr = np.random.rand(4, 4)
print("Original array:\n", arr)

# Add a border of zeros around the array
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Array with zero border:\n", bordered_arr)


Original array:
 [[0.73886481 0.25275987 0.66823381 0.24907584]
 [0.19674406 0.57114197 0.25372812 0.50186788]
 [0.16790636 0.44020556 0.2611794  0.99794527]
 [0.27291181 0.84321573 0.61569062 0.84325984]]
Array with zero border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.73886481 0.25275987 0.66823381 0.24907584 0.        ]
 [0.         0.19674406 0.57114197 0.25372812 0.50186788 0.        ]
 [0.         0.16790636 0.44020556 0.2611794  0.99794527 0.        ]
 [0.         0.27291181 0.84321573 0.61569062 0.84325984 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [5]:
#4. Create Array from 10 to 60 with Step 5:
import numpy as np
arr = np.arange(10, 65, 5)
print("Array:", arr)

   

Array: [10 15 20 25 30 35 40 45 50 55 60]


In [6]:
#5. String Case Transformations:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Convert to uppercase
upper = np.char.upper(arr)
print("Uppercase:", upper)

# Convert to lowercase
lower = np.char.lower(arr)
print("Lowercase:", lower)

# Convert to title case
title = np.char.title(arr)
print("Title case:", title)

   

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


In [7]:
#6. Insert Spaces Between Characters:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Insert spaces between characters
spaced = np.char.join(' ', arr)
print("Spaced characters:", spaced)



Spaced characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


In [8]:
#7. Element-wise Operations on 2D Arrays:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:
#8. Create Identity Matrix and Extract Diagonal:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:\n", identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [10]:
#9. Find Prime Numbers in Array:
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, 100)

# Define a function to check if a number is prime
def is_prime(x):
    if x < 2:
        return False
    for i in range(2, int(np.sqrt(x)) + 1):
        if x % i == 0:
            return False
    return True

# Vectorize the prime-checking function
vectorized_is_prime = np.vectorize(is_prime)

# Apply the vectorized function to the array
primes = arr[vectorized_is_prime(arr)]

print("Random Array:", arr)
print("Prime Numbers:", primes)


Random Array: [162 948 526 716 700 277 816 558 398 179 370 984 640 387 919 183 573 288
 593 982 298 259 318  44 257 736 679 899 827 591 648 337 209  29 961 383
 878 108 708 652 228 764 495 458  32 385 332 182 995 638 769 594  62 907
 263 261 331 864 370 608 717 570 568 611 436 183 975 659 630 152 891 774
 705  39 786 571   9 540 728 476 378 241 924  75 364 858 460 582 486 679
 615 107 280 343 309 588 598 432 932 918]
Prime Numbers: [277 179 919 593 257 827 337  29 383 769 907 263 331 659 571 241 107]


In [11]:
#10. Calculate Weekly Averages from Daily Temperatures:

import numpy as np

# Generate an array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, 100)

# Define a function to check if a number is prime
def is_prime(x):
    if x < 2:
        return False
    for i in range(2, int(np.sqrt(x)) + 1):
        if x % i == 0:
            return False
    return True

# Vectorize the prime-checking function
vectorized_is_prime = np.vectorize(is_prime)

# Apply the vectorized function to the array
primes = arr[vectorized_is_prime(arr)]

print("Random Array:", arr)
print("Prime Numbers:", primes)


Random Array: [443  94 151 415 594 807 540 636 752  47 491 929 407 673 136  72 357 845
 114 760 919 819 206 636 601 209 124  53 923 353 808 365  20 816 860 887
 236 349 658 295 634  48 631 556 903 293 575 561 166 762 128 960 124 917
 537 298 857 755 650 286 361 787 747 851 213 670 679 670 171 781 205 965
 179 826 730 294 877 775 652 264 485 272  94 438 844 432 739 926 979 671
 938 174 755 580 891 454 673  47 543 907]
Prime Numbers: [443 151  47 491 929 673 919 601  53 353 887 349 631 293 857 787 179 877
 739 673  47 907]
